# Open Source Development Platform
osdp:
  # details
  linux: amazon   # So we can develop AWS Lambda with same python version
  username: jknott    # one of the siblings
  project: company
  platform: docker # Currently supported docker and vagrant
  runtime: python3.6
  dockerhubusername: buildmystartup
  dockerhubpassword: mypassword
  imagename: buildmystartup/ghettolabs
  pushto: ghettolabs/python
  dockerdeveloperimage: buildmystartup/ghettolabs:python3.6
