# Open Source Development Platform
osdp:
  # details
  linux: amazon   # So we can develop AWS Lambda with same python version
  username: james-knott
  password: mypassword
  project: company
  configs: https://github.com/james-knott/configuration.git
  platform: vagrant 
  runtime: python3.6
  dockerhubusername: buildmystartup
  dockerhubpassword: mypassword
  imagename: buildmystartup/ghettolabs
  pushto: ghettolabs/python
  dockerhome: /Users
  dockerdeveloperimage: buildmystartup/ghettolabs:python3.6
